export const KarenCorePrinciples = {
  AI_CANNOT_MUTATE_STATE_DIRECTLY: true,
  EVENTS_ARE_IMMUTABLE: true,
  SENSITIVE_DATA_NEVER_REACHES_MODELS: true,
  REMINDERS_ARE_BOUNDED: true,
  HUMAN_OVERRIDE_ALWAYS_WINS: true,
  TOOLS_ARE_ZERO_TRUST: true,
  DETERMINISTIC_VALIDATION_PRECEDES_EXECUTION: true
} as const;

export const BoundedAutonomyConfigs = {
  MAX_REMINDERS_PER_TASK: 3,
  MAX_PROACTIVE_MESSAGES_PER_HOUR: 2,
  MAX_ESCALATION_LEVEL: 3,
  MAX_AI_CALLS_PER_MINUTE: 10
} as const;

export enum RetryClassification {
  RETRYABLE = 'RETRYABLE',
  NON_RETRYABLE = 'NON_RETRYABLE',
  MANUAL_INTERVENTION = 'MANUAL_INTERVENTION',
  DELAYED_RETRY = 'DELAYED_RETRY'
}
